spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    problemdetails:
      enabled: true
  main:
    web-application-type: servlet
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:mysql://localhost:3306/shopee
    username: quandev03
    password: Ngoquan03
    jwt:
      secret: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

server:
  error:
    include-message: always
    include-binding-errors: always
APP_NAME: Shopee