spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    problemdetails:
      enabled: true
  main:
    web-application-type: servlet
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:mysql://34.46.178.207:3306/shopee
    username: root
    password: Ngoquan@2003
    jwt:
      secret: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

server:
  error:
    include-message: always
    include-binding-errors: always
  address: 0.0.0.0
  port: 8080
APP_NAME: Shopee
logging:
  level:
    org.springdoc: DEBUG