spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jwt:
      secret: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    producer:
      enabled: ${KAFKA_PRODUCER_ENABLED}
    consumer:
      enabled: ${KAFKA_CONSUMER_ENABLED}
    host: ${KAFKA_HOST}
    port: ${KAFKA_PORT}
    url: ${KAFKA_URL}
    group: ${KAFKA_GROUP}

  firebase:
    url: ${URL_FIREBASE}
    bucketname: ${BUCKET_NAME}




grpc:
  client:
    searchService:
      address: ${GRPC_SEARCH_SERVICE_ADDRESS}
      negotiationType: ${GRPC_SEARCH_SERVICE_NEGOTIATION_TYPE}

