spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    problemdetails:
      enabled: true
  main:
    web-application-type: servlet
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:mysql://localhost:3306/shopee
    username: quandev03
    password: Ngoquan03
    jwt:
      secret: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    producer:
      enabled: ${KAFKA_PRODUCER_ENABLED}
    consumer:
      enabled: ${KAFKA_CONSUMER_ENABLED}
    host: ${KAFKA_HOST}
    port: ${KAFKA_PORT}
    url: ${KAFKA_URL}
    group: ${KAFKA_GROUP}

  firebase:
    url: ${URL_FIREBASE}
    bucketname: ${BUCKET_NAME}
  fe:
    baseurl:${URL_FE}




grpc:
  client:
    searchService:
      address: ${GRPC_SEARCH_SERVICE_ADDRESS}
      negotiationType: ${GRPC_SEARCH_SERVICE_NEGOTIATION_TYPE}

server:
  error:
    include-message: always
    include-binding-errors: always
APP_NAME: Shopee